# Generated by Django 2.1.8 on 2019-11-04 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PUser', '0002_user_identity'),
        ('Buyer', '0002_auto_20191104_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_time', models.CharField(max_length=32)),
                ('goods_number', models.IntegerField()),
                ('goods_price', models.FloatField()),
                ('goods_total', models.FloatField(default=0)),
                ('goods_picture', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Pay_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=32)),
                ('order_time', models.DateTimeField(auto_now=True)),
                ('order_number', models.IntegerField()),
                ('order_total', models.FloatField(default=0)),
                ('order_state', models.IntegerField(default=0)),
                ('order_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PUser.User')),
            ],
        ),
        migrations.AddField(
            model_name='order_info',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyer.Pay_order'),
        ),
        migrations.AddField(
            model_name='order_info',
            name='order_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PUser.User'),
        ),
    ]
