# Generated by Django 2.1.8 on 2019-11-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0004_auto_20191104_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_info',
            name='goods_picture',
            field=models.CharField(max_length=64),
        ),
    ]
