# Generated by Django 2.1.8 on 2019-11-05 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0007_goodsaddress_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoodsAddress',
        ),
    ]
