# Generated by Django 2.1.8 on 2019-10-29 05:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PShop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
