# Generated by Django 2.1.8 on 2019-10-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PShop', '0003_goods_statue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='statue',
            field=models.IntegerField(null=True),
        ),
    ]
