# Generated by Django 2.1.8 on 2019-10-31 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PUser', '0002_user_identity'),
        ('PShop', '0005_auto_20191030_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PUser.User'),
            preserve_default=False,
        ),
    ]
