# Generated by Django 2.1.8 on 2019-11-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PUser', '0002_user_identity'),
        ('PShop', '0006_goods_goods_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_cart_user',
            field=models.ManyToManyField(related_name='cart_user', to='PUser.User'),
        ),
    ]
