# Generated by Django 2.1.8 on 2019-11-04 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PShop', '0007_goods_goods_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='goods_cart_user',
        ),
    ]
