# Generated by Django 2.1.8 on 2019-11-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PUser', '0004_goodsaddress_all_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsaddress',
            name='uesr',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
