# Generated by Django 2.1.8 on 2019-11-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PUser', '0005_goodsaddress_uesr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsaddress',
            old_name='uesr',
            new_name='user_email',
        ),
        migrations.AlterField(
            model_name='goodsaddress',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
